project:
  type: website
  output-dir: docs

format: 
  html: 
    page-layout: full

theme: 
  light: flatly
  dark: darkly

website:
  title: DSML - Related
  search: true
  repo-url: https://github.com/rabchl/dsml-related
  repo-actions: [issue]
  reader-mode: true
  page-navigation: true
  
  sidebar:
    - subtitle: "SOTA stuff"
      style: "floating"
      type: dark
      background: dark
      foreground: light
      border: true
      collapse-level: 2
      tools: 
        - icon: twitter
          href: https://twitter.com
      contents:
        - 00-how-to-use-this-book.qmd
        - section: "AWS"
          contents:
            - aws-iam.qmd
