project:
  type: website
  output-dir: docs

format: 
  html: 
    page-layout: full

theme: 
  light: flatly
  dark: [darkly, theme-dark.scss]

website:
  title: DSML - Related
  search: true
  repo-url: https://github.com/rabchl/dsml-related
  repo-actions: [issue]
  reader-mode: true
  page-navigation: true
  
  sidebar:
    - subtitle: "SOTA stuff"
      style: "floating"
      type: dark
      background: dark
      foreground: light
      border: true
      collapse-level: 2
      tools: 
        - icon: twitter
          href: https://twitter.com

      contents:
        - 00-how-to-use-this-site.qmd

        - section: "AWS"
          contents:
            - section: "IAM"
              contents:
                - aws-iam.qmd
                - aws-iam-auth.qmd
                - aws-iam-sts.qmd
                - aws-iam-sign-in-link.qmd
                - aws-iam-billing-alarm.qmd
                - aws-iam-creating-users.qmd
                - aws-iam-pass-policy.qmd
            - section: "Infrastructure"
              contents:
                - aws-infra.qmd
                - aws-infra-vpc.qmd

        - section: "Production-Ready Development"
          contents:
            - production-ready.qmd
            - section: "Machine Learning Projects"
              contents: 
                - production-ready-planning.qmd
                - production-ready-mvp.qmd
                - production-ready-ffp.qmd
                - production-ready-deploy-maintenance.qmd
                - production-ready-evaluation.qmd
        
        - section: "Environments"
          contents:
            - venv-conda.qmd

        - section: "Data Engineering"
          contents:
            - deng.qmd
            - deng-data-collection.qmd
