---
title: "Effective Project Planning"
---

1. The project lead **must** 
    - clearly define what is the purpose of the project (new product, improve existing service, save operational cost)
    - clearly define what needs to be achieved by the project
    - understand groups that can affect or be affected by the project (stakeholders). 

2. The evaluations metrics need to be defined and agreed upon as they will be revisited during project evaluation.
    - Business-related metrics
    - Model-based metrics
    - Due dates
    - Resource usage (available resources)
    - Tradeoffs can be made between the various metrics. Slight decrease in accuracy may be acceptable if meeting latency requirements is more critical to the project.

3. Team members group together to discuss
    - how to achieve business objectives using available resources.
    - _key_ members should have a thorough understanding of the available resources that can be allocated to the project.
    - individual responsabilities as well as stakeholders responsabilities

4. Define milestones and their associated tasks
    - A milestone refers to a point in a project where a significant event occurs
    - The ordering of tasks that lead to the goal is called the **_critical path_**
    - Available resources need to be allocated to each task
    - set aside a portion of the resources as a backup

5. Establish the timeline, an estimate of how long the project would be.

6. Generate a _well-documented_ project playbook, a thorough description of how the project will be carried out, evaluated and defines business objectives. Refer to PMBOK or PRINCE2.
    - Overview of key deliverables
    - List of stakeholders
    - Gantt chart defining steps and bottlenecks
    - Definition of responsabilities
    - Timelines
    - Evaluation criteria

7. Once the playbook is constructed, every stakeholder must review and revise it until everyone agrees with the contents.

8. Define the process that the team will follow to update other team members and ensure on-time delivery of the project.
    - Select a project management methodologies